Update parser for move records with comments
nozaq/csa-rs pull request #18
Opened 2022-03-13 13:59 UTC by sugyan

I tried to parse CSA files from [floodgate](http://wdoor.c.u-tokyo.ac.jp/shogi/floodgate.html) archives, but it didn't work well.
These records may contain the comment line in each move record.

```
+7776FU
'*jouseki
```

```
+7776FU
'** 30 -3334FU +2726FU
```

http://shogi-server.osdn.jp/protocol.html#record-pv

This parser stopped parsing with the first comment line on the move records block.

2022-03-15 22:01 UTC, nozaq requested changes
@sugyan Thank you for your contribution!
The PR almost looks good to me, could you fix one clippy warning regarding `unwrap_or_else()` call?

2022-03-16 06:22 UTC, sugyan commented
@nozaq Thanks for your review. I fixed it.

2022-03-16 06:34 UTC, nozaq approved these changes
Thank you, LGTM!

2022-03-16 06:34 UTC, merged

2022-03-16 14:08 UTC, nozaq commented
Released in v1.0.1 🎉